### ISSUE TITLE
Feature: Add support for per-image public setting

### ISSUE THREAD

**Issue by cityofships** [stackhpc/ansible-role-os-images#46]
Currently either all images uploaded by the role are public or none.

**Comment by priteau** [comment]
I don't remember why I didn't merge this. Did you try it?

**Comment by cityofships** [comment]
Not yet. Just rebased the source branch, might get to testing it and making a docs update.

**Comment by cityofships** [comment]
I tested this - setting an owner does not work for me, maybe a bug in `os_module`?

Setting images as private worked, there is a follow up PR: #50

**Comment by priteau** [comment]
I remember issues but not the details, maybe this is why I didn't push it.
